[package]
name = "yoke"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
clap = { version = "4.5", features = ["derive"] }
notify = "6.1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
shellexpand = "3.1"
subtle = "2.6.1"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8"
tower = { version = "0.4", features = ["util"] }
tower-http = { version = "0.5", features = ["limit", "trace", "cors"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
url = { version = "2.5", features = ["serde"] }
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
thiserror = "2"
git2 = "0.19"
arc-swap = "1.9.1"

[dev-dependencies]
tempfile = "3"
